http {
  port = 8080
}

database {
  hikari {
    jdbcUrl = "jdbc:sqlite:twodeeweb.sqlite3"

    maximumPoolSize = 1
    minimumIdle = 0

    connectionTimeout=10000
    idleTimeout=10000
    maxLifetime=30000

    leakDetectionThreshold=5000
  }
}